name: 'Action Expose'
description: 'GitHub Action para exportar as secrets.'
author: 'WeeNow'

# Define your inputs here.
inputs:
  secrets:
    required: true
    description: Use a função toJSON ${{ toJSON(secrets) }}.
  prefix:
    required: false
    description: 'Prefixo das secrets que deseja expor, e.g.: EXP_'
runs:
  using: node20
  main: dist/index.js
